name: elapsed_timer
description: A package contains ElapsedTimer, which allows easy access to the elapsed time of your timer.
version: 0.1.0
homepage: https://github.com/KabaDH/elapsed_timer

environment:
  sdk: '>=3.4.3 <4.0.0'

dev_dependencies:
  test: ^1.25.7

topics:
  - timer
  - elapsed-time